// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace OpenCBS.AcceptanceTest.Repayment
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Simple early repayment")]
    public partial class SimpleEarlyRepaymentFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Simple early repayment.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Simple early repayment", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Simple early repayment")]
        public virtual void SimpleEarlyRepayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Simple early repayment", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table1.AddRow(new string[] {
                        "USE_CENTS",
                        "Yes"});
            table1.AddRow(new string[] {
                        "INCREMENTAL_DURING_DAYOFFS",
                        "Yes"});
            table1.AddRow(new string[] {
                        "ACCOUNTING_PROCESS",
                        "Accrual"});
            table1.AddRow(new string[] {
                        "USE_DAILY_ACCRUAL_OF_PENALTY",
                        "False"});
#line 5
    testRunner.Given("these settings", ((string)(null)), table1, "Given ");
#line 11
    testRunner.And("the \"ANNUITY\" loan product", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table2.AddRow(new string[] {
                        "Installments",
                        "12"});
            table2.AddRow(new string[] {
                        "Amount",
                        "10000"});
            table2.AddRow(new string[] {
                        "Interest rate",
                        "0,03"});
            table2.AddRow(new string[] {
                        "Grace period",
                        "0"});
            table2.AddRow(new string[] {
                        "Rounding",
                        "End"});
            table2.AddRow(new string[] {
                        "Start date",
                        "11.06.2013"});
            table2.AddRow(new string[] {
                        "First installment date",
                        "11.07.2013"});
#line 13
    testRunner.When("I create a loan", ((string)(null)), table2, "When ");
#line 22
    testRunner.And("I set line of credit limit to 100000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
    testRunner.And("I disburse on 11.06.2013", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Number",
                        "Expected date",
                        "Expected interest",
                        "Expected principal",
                        "Expected total",
                        "Olb",
                        "Paid principal",
                        "Paid interest"});
            table3.AddRow(new string[] {
                        "1",
                        "11.07.2013",
                        "300",
                        "705",
                        "1005",
                        "10000",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "2",
                        "12.08.2013",
                        "279",
                        "726",
                        "1005",
                        "9295",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "3",
                        "11.09.2013",
                        "257",
                        "748",
                        "1005",
                        "8569",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "4",
                        "11.10.2013",
                        "235",
                        "770",
                        "1005",
                        "7821",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "5",
                        "11.11.2013",
                        "212",
                        "793",
                        "1005",
                        "7051",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "6",
                        "11.12.2013",
                        "188",
                        "817",
                        "1005",
                        "6258",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "7",
                        "13.01.2014",
                        "163",
                        "842",
                        "1005",
                        "5441",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "8",
                        "11.02.2014",
                        "138",
                        "867",
                        "1005",
                        "4599",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "9",
                        "11.03.2014",
                        "112",
                        "893",
                        "1005",
                        "3732",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "10",
                        "11.04.2014",
                        "85",
                        "920",
                        "1005",
                        "2839",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "11",
                        "12.05.2014",
                        "58",
                        "947",
                        "1005",
                        "1919",
                        "0",
                        "0"});
            table3.AddRow(new string[] {
                        "12",
                        "11.06.2014",
                        "29",
                        "972",
                        "1001",
                        "972",
                        "0",
                        "0"});
#line 25
    testRunner.Then("the schedule is", ((string)(null)), table3, "Then ");
#line 41
    testRunner.When("I repay 2010 on 11.07.2013", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Number",
                        "Expected date",
                        "Expected interest",
                        "Expected principal",
                        "Expected total",
                        "Olb",
                        "Paid principal",
                        "Paid interest"});
            table4.AddRow(new string[] {
                        "1",
                        "11.07.2013",
                        "300",
                        "705",
                        "0",
                        "10000",
                        "705",
                        "300"});
            table4.AddRow(new string[] {
                        "2",
                        "12.08.2013",
                        "279",
                        "726",
                        "0",
                        "9295",
                        "726",
                        "279"});
            table4.AddRow(new string[] {
                        "3",
                        "11.09.2013",
                        "257",
                        "748",
                        "1005",
                        "8569",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "4",
                        "11.10.2013",
                        "235",
                        "770",
                        "1005",
                        "7821",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "5",
                        "11.11.2013",
                        "212",
                        "793",
                        "1005",
                        "7051",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "6",
                        "11.12.2013",
                        "188",
                        "817",
                        "1005",
                        "6258",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "7",
                        "13.01.2014",
                        "163",
                        "842",
                        "1005",
                        "5441",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "8",
                        "11.02.2014",
                        "138",
                        "867",
                        "1005",
                        "4599",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "9",
                        "11.03.2014",
                        "112",
                        "893",
                        "1005",
                        "3732",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "10",
                        "11.04.2014",
                        "85",
                        "920",
                        "1005",
                        "2839",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "11",
                        "12.05.2014",
                        "58",
                        "947",
                        "1005",
                        "1919",
                        "0",
                        "0"});
            table4.AddRow(new string[] {
                        "12",
                        "11.06.2014",
                        "29",
                        "972",
                        "1001",
                        "972",
                        "0",
                        "0"});
#line 43
    testRunner.Then("the schedule is", ((string)(null)), table4, "Then ");
#line 65
    testRunner.When("I repay 4500 on 22.08.2013 with no keep schedule", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Number",
                        "Expected date",
                        "Expected interest",
                        "Expected principal",
                        "Expected total",
                        "Olb",
                        "Paid principal",
                        "Paid interest"});
            table5.AddRow(new string[] {
                        "1",
                        "11.07.2013",
                        "300",
                        "705",
                        "0",
                        "10000",
                        "705",
                        "300"});
            table5.AddRow(new string[] {
                        "2",
                        "12.08.2013",
                        "279",
                        "726",
                        "0",
                        "9295",
                        "726",
                        "279"});
            table5.AddRow(new string[] {
                        "3",
                        "22.08.2013",
                        "86",
                        "4414",
                        "0",
                        "8569",
                        "4414",
                        "86"});
            table5.AddRow(new string[] {
                        "4",
                        "11.09.2013",
                        "83",
                        "362",
                        "487",
                        "4155",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "5",
                        "11.10.2013",
                        "114",
                        "373",
                        "487",
                        "3793",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "6",
                        "11.11.2013",
                        "103",
                        "384",
                        "487",
                        "3420",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "7",
                        "11.12.2013",
                        "91",
                        "396",
                        "487",
                        "3036",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "8",
                        "13.01.2014",
                        "79",
                        "408",
                        "487",
                        "2640",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "9",
                        "11.02.2014",
                        "67",
                        "420",
                        "487",
                        "2232",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "10",
                        "11.03.2014",
                        "54",
                        "433",
                        "487",
                        "1812",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "11",
                        "11.04.2014",
                        "41",
                        "446",
                        "487",
                        "1379",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "12",
                        "12.05.2014",
                        "28",
                        "459",
                        "487",
                        "933",
                        "0",
                        "0"});
            table5.AddRow(new string[] {
                        "13",
                        "11.06.2014",
                        "14",
                        "474",
                        "488",
                        "474",
                        "0",
                        "0"});
#line 67
    testRunner.Then("the schedule is", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
